# Generated by Django 4.0.5 on 2022-07-04 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Фильм')),
                ('price', models.IntegerField(verbose_name='Стоимость просмотра')),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Отель')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.city', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Отель',
                'verbose_name_plural': 'Отели',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Тариф')),
                ('price', models.IntegerField(verbose_name='Цена (руб./мин.)')),
                ('hotel', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='billing.hotel', verbose_name='Название отеля')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.film', verbose_name='Бонус')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
            },
        ),
        migrations.CreateModel(
            name='RoomDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Стандарт 500', max_length=50, verbose_name='Депозит номера')),
                ('balance', models.IntegerField(verbose_name='Баланс')),
            ],
            options={
                'verbose_name': 'Депозит номера',
                'verbose_name_plural': 'Депозиты',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Категория номера')),
                ('deposit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.roomdeposit', verbose_name='Баланс ТВ')),
                ('film', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='billing.film', verbose_name='Фильм включен')),
                ('hotel', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='billing.hotel', verbose_name='Отель')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.plan', verbose_name='Тариф включен')),
            ],
            options={
                'verbose_name': 'Категория номера',
                'verbose_name_plural': 'Категории номера',
            },
        ),
    ]
