# Generated by Django 4.0.5 on 2022-06-29 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotel',
            options={'verbose_name': 'Отель', 'verbose_name_plural': 'Отели'},
        ),
        migrations.RemoveField(
            model_name='plan',
            name='movie1',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='movie2',
        ),
        migrations.AddField(
            model_name='plan',
            name='movie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='billing.film', verbose_name='Бонус'),
            preserve_default=False,
        ),
    ]
