# Generated by Django 4.0.5 on 2022-06-29 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_alter_hotel_options_remove_plan_movie1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomdeposit',
            name='category',
        ),
    ]
