# Generated by Django 4.0.5 on 2022-06-29 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_roomdeposit_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='hotel',
        ),
    ]
