# Generated by Django 4.0.5 on 2022-06-29 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_remove_room_hotel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roomdeposit',
            options={'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
    ]
