# Generated by Django 4.0.5 on 2022-06-29 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_alter_roomdeposit_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='hotel',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='billing.hotel', verbose_name='Название отеля'),
        ),
    ]
