# Generated by Django 4.0.5 on 2022-06-29 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_plan_hotel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roomdeposit',
            options={'verbose_name': 'Депозит номера', 'verbose_name_plural': 'Депозиты'},
        ),
        migrations.AlterField(
            model_name='roomdeposit',
            name='name',
            field=models.CharField(default='Стандарт 500', max_length=50, verbose_name='Депозит номера'),
        ),
    ]
