# Generated by Django 4.0.5 on 2022-06-30 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_room_film_room_hotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='deposit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.roomdeposit', verbose_name='Баланс ТВ'),
        ),
    ]
