# Generated by Django 4.0.5 on 2022-06-30 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_managerhotel_managers_managerhotel_is_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='managerhotel',
            old_name='name',
            new_name='username',
        ),
    ]
