# Generated by Django 4.0.5 on 2022-06-30 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_managerhotel_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managerhotel',
            name='is_staff',
        ),
    ]
